from pydantic import BaseModel, Field
from typing import Optional, List, Tuple
from enum import Enum


class AuditStatus(str, Enum):
    COMPLIANT = "Compliant"
    PARTIAL = "Partial"
    GAP = "Gap"
    REQUIRES_HUMAN_REVIEW = "Requires Human Review"
    INFORMATIONAL = "Informational"


class GraphNodeType(str, Enum):
    AGENCY = "Agency"
    REGULATION = "Regulation"
    AMC_GM = "AMC_GM"
    MANUAL_SECTION = "ManualSection"
    DIAGRAM = "Diagram"
    TECHNICAL_LIMIT = "TechnicalLimit"


class EdgeType(str, Enum):
    MANDATES = "MANDATES"
    CLARIFIES = "CLARIFIES"
    REFERENCES = "REFERENCES"
    CONFLICTS_WITH = "CONFLICTS_WITH"
    CONTAINS_DIAGRAM = "CONTAINS_DIAGRAM"


class EasaRequirement(BaseModel):
    """
    Represents a specific regulation or requirement from the EASA Easy Access Rules.
    Strictly mapped to the EASA XML metadata attributes.
    """
    id: str = Field(..., description="The unique identifier, mapped from 'ERulesId'")
    text: str = Field(..., description="The full text of the requirement, extracted from <para> tags")
    type: str = Field(..., description="The type of requirement, e.g., 'Implementing Rule', 'AMC'")
    version: Optional[str] = Field(None, description="The version or revision number if applicable")

    # New fields for production-grade schema
    source_title: Optional[str] = Field(None, description="The heading/title of the topic context")
    domain: Optional[str] = Field(None, description="The regulatory domain, e.g., 'ADR', 'ORO'")
    applicability_date: Optional[str] = Field(None, description="The date this requirement becomes applicable")
    amc_gm_info: Optional[str] = Field(None, description="Categorization for Hard Law vs Soft Law based on TypeOfContent or EASACategory")


class ManualChunk(BaseModel):
    """
    Represents a logical chunk from an Airline Operator Manual.
    """
    page_number: int = Field(..., description="The page number where this chunk starts")
    section_title: str = Field(..., description="The logical section title, e.g., '4.1 Safety Policy'")
    content: str = Field(..., description="The textual content of the chunk")
    file_hash: str = Field(..., description="A hash of the source PDF to uniquely identify the document version")

    # Visual evidence traceability
    bbox: Optional[Tuple[float, float, float, float]] = Field(
        None, description="Bounding box (x0, y0, x1, y1) for visual traceability"
    )
    has_diagram: bool = Field(False, description="Whether this chunk contains visual elements (tables, diagrams)")
    diagram_path: Optional[str] = Field(None, description="Path to extracted crop image of diagram/table")


class ComplianceAudit(BaseModel):
    """
    Represents the result of an AI compliance check for a specific EASA requirement against the manual chunks.
    """
    requirement_id: str = Field(..., description="The ID of the EASA requirement being checked")
    status: AuditStatus = Field(..., description="The compliance status")
    evidence_quote: str = Field(..., description="The exact sentence(s) from the manual used as proof")
    source_reference: str = Field(..., description="Source citation, e.g., 'Page 42, Paragraph 4.1.2'")
    confidence_score: float = Field(..., description="A score from 0.0 to 1.0 indicating AI confidence")
    suggested_fix: Optional[str] = Field(None, description="Suggested fix generated by Gemini if a Gap or Partial compliance is found.")

    # GraphRAG traceability fields
    cross_refs_used: List[str] = Field(default_factory=list, description="IDs of rules used in regulatory chain analysis")
    validation_score: Optional[float] = Field(None, description="CriticAgent's verification score (0.0-1.0)")
    evidence_crop_path: Optional[str] = Field(None, description="Path to visual evidence crop image")
    agent_trace: Optional[str] = Field(None, description="Pipeline trace: which agents contributed to this result")


class GraphNode(BaseModel):
    """Represents a node in the regulatory knowledge graph."""
    id: str = Field(..., description="Unique node identifier")
    node_type: GraphNodeType = Field(..., description="Type of node")
    label: str = Field(..., description="Human-readable label for display")
    domain: Optional[str] = Field(None, description="Regulatory domain")
    properties: dict = Field(default_factory=dict, description="Additional metadata")


class GraphEdge(BaseModel):
    """Represents an edge in the regulatory knowledge graph."""
    source: str = Field(..., description="Source node ID")
    target: str = Field(..., description="Target node ID")
    edge_type: EdgeType = Field(..., description="Type of relationship")
    weight: float = Field(1.0, description="Edge weight for graph traversal")
    properties: dict = Field(default_factory=dict, description="Additional metadata")
